<?php
/**
 * @file unsaved_node_warning.module
 */
 
function unsaved_node_warning_form_alter(&$form, $form_state, $form_id) {
  if (_unw_is_node_edit($form, $form_id)) {
    drupal_add_js(drupal_get_path('module', 'unsaved_node_warning') . '/unsaved_node_warning.js');
  }
}

/**
 * Is this a node edit form?
 */
function _unw_is_node_edit($form, $form_id) {
  return isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id;
}



